window.PUSH_DATA = {
  merchant: {
    id: "m_001",
    name: "Bodega Azul",
    plan: "Growth",
    city: "Williamsburg, NYC",
    logo: "P",
  },
  nav: [
    { id: "dashboard", label: "Dashboard", emoji: "📊", section: "Core" },
    { id: "campaigns", label: "Campaigns", emoji: "🚀", section: "Core" },
    { id: "applicants", label: "Applicants", emoji: "🧑‍🎨", section: "Core" },
    { id: "analytics", label: "Analytics", emoji: "📈", section: "Core" },
    { id: "qr", label: "QR Codes", emoji: "🔳", section: "Operations" },
    { id: "locations", label: "Locations", emoji: "📍", section: "Operations" },
    { id: "disputes", label: "Disputes", emoji: "🛡️", section: "Operations" },
    { id: "messages", label: "Messages", emoji: "💬", section: "Operations" },
    { id: "payments", label: "Payments", emoji: "💸", section: "Business" },
    { id: "billing", label: "Billing", emoji: "🧾", section: "Business" },
    { id: "integrations", label: "Integrations", emoji: "🔌", section: "Business" },
    { id: "notifications", label: "Notifications", emoji: "🔔", section: "Account" },
    { id: "settings", label: "Settings", emoji: "⚙️", section: "Account" },
  ],
  kpi: {
    verified_visits_today: 47,
    active_campaigns: 3,
    applicants_today: 6,
    attributed_revenue_today: 1504,
    avg_roi_30d: 3.9,
    open_disputes: 2,
    qr_scans_today: 1210,
    repeat_rate_30d: 32.9,
  },
  campaigns: [
    {
      id: "c_201",
      title: "Spring Matcha Drop",
      status: "Live",
      budget: 1200,
      spent: 740,
      verified_visits: 63,
      goal_visits: 90,
      conversion_rate: 18.2,
      top_creator: "Maya Lin",
      start: "2026-04-15",
      end: "2026-05-02",
    },
    {
      id: "c_202",
      title: "Morning Combo Push",
      status: "Live",
      budget: 900,
      spent: 420,
      verified_visits: 41,
      goal_visits: 70,
      conversion_rate: 14.7,
      top_creator: "Jin Carter",
      start: "2026-04-18",
      end: "2026-04-30",
    },
    {
      id: "c_203",
      title: "Weekend Late-Night",
      status: "Draft",
      budget: 600,
      spent: 0,
      verified_visits: 0,
      goal_visits: 40,
      conversion_rate: 0,
      top_creator: "Pending",
      start: "2026-04-26",
      end: "2026-05-09",
    },
  ],
  applicants: [
    {
      id: "a_101",
      name: "Maya Lin",
      role: "Coffee + Lifestyle Creator",
      tier: "Operator",
      followers: 8200,
      match_score: 94,
      est_visits_7d: 18,
      est_revenue_7d: 620,
      completion: 91,
      badge: "Top Local Fit",
      avatar: "🧑‍🎤",
      tone: "violet",
      location: "Williamsburg",
      style: "Short-form reels, UGC storytelling",
    },
    {
      id: "a_102",
      name: "Noah Park",
      role: "Food Reels Creator",
      tier: "Explorer",
      followers: 2400,
      match_score: 88,
      est_visits_7d: 11,
      est_revenue_7d: 370,
      completion: 84,
      badge: "High CTR",
      avatar: "🧑‍🍳",
      tone: "amber",
      location: "Greenpoint",
      style: "Fast edits, promo hooks under 8s",
    },
    {
      id: "a_103",
      name: "Ari Santos",
      role: "Neighborhood Creator",
      tier: "Proven",
      followers: 19600,
      match_score: 92,
      est_visits_7d: 15,
      est_revenue_7d: 560,
      completion: 87,
      badge: "Strong Repeat Buyers",
      avatar: "🧑‍💼",
      tone: "teal",
      location: "East Village",
      style: "Event-style story sequences",
    },
    {
      id: "a_104",
      name: "Rin Cho",
      role: "Campus Creator",
      tier: "Seed",
      followers: 930,
      match_score: 79,
      est_visits_7d: 7,
      est_revenue_7d: 220,
      completion: 73,
      badge: "Emerging",
      avatar: "🧑‍🎓",
      tone: "mint",
      location: "Lower Manhattan",
      style: "Community and student audience",
    },
  ],
  analytics: {
    impressions: 48200,
    qr_scans: 1210,
    verified_visits: 286,
    repeat_customers: 94,
    revenue: 8240,
    by_hour: [6, 8, 12, 14, 18, 21, 25, 28, 31, 35, 37, 34],
    funnel: [
      { label: "Impressions", value: 48200 },
      { label: "QR Scans", value: 1210 },
      { label: "Verified Visits", value: 286 },
      { label: "Repeat Visits", value: 94 },
    ],
    creators: [
      { name: "Maya Lin", visits: 72, revenue: 2310 },
      { name: "Jin Carter", visits: 55, revenue: 1780 },
      { name: "Ari Santos", visits: 44, revenue: 1420 },
      { name: "Noah Park", visits: 38, revenue: 1080 },
    ],
  },
  qr_codes: [
    {
      id: "qr_401",
      creator: "Maya Lin",
      campaign: "Spring Matcha Drop",
      scans_today: 47,
      verified_today: 15,
      fraud_flags: 1,
      status: "Active",
    },
    {
      id: "qr_402",
      creator: "Jin Carter",
      campaign: "Morning Combo Push",
      scans_today: 29,
      verified_today: 10,
      fraud_flags: 0,
      status: "Active",
    },
    {
      id: "qr_403",
      creator: "Ari Santos",
      campaign: "Spring Matcha Drop",
      scans_today: 18,
      verified_today: 7,
      fraud_flags: 0,
      status: "Active",
    },
  ],
  locations: [
    {
      id: "loc_301",
      name: "Main Store",
      address: "420 Bedford Ave, Brooklyn, NY",
      lat: 40.7176,
      lng: -73.9572,
      visits_today: 29,
      peak_hour: "08:00 - 10:00",
      radius: 120,
    },
    {
      id: "loc_302",
      name: "Annex Counter",
      address: "97 N 6th St, Brooklyn, NY",
      lat: 40.7211,
      lng: -73.9508,
      visits_today: 18,
      peak_hour: "12:00 - 14:00",
      radius: 90,
    },
    {
      id: "loc_303",
      name: "Pop-up Cart",
      address: "Domino Park, Brooklyn, NY",
      lat: 40.7164,
      lng: -73.9685,
      visits_today: 11,
      peak_hour: "17:00 - 19:00",
      radius: 80,
    },
  ],
  disputes: [
    {
      id: "d_501",
      type: "Duplicate Scan Pattern",
      amount: 38,
      priority: "Medium",
      status: "Under Review",
      opened_at: "2026-04-22 10:24",
      owner: "Fraud Analyst",
    },
    {
      id: "d_502",
      type: "Late Claim Redemption",
      amount: 21,
      priority: "Low",
      status: "Pending Merchant Reply",
      opened_at: "2026-04-22 19:40",
      owner: "Operations",
    },
  ],
  messages: [
    {
      id: "t_601",
      from: "Maya Lin",
      subject: "Content draft approval",
      unread: 2,
      last: "Need final CTA wording for story frame #2",
      time: "00:18",
    },
    {
      id: "t_602",
      from: "Jin Carter",
      subject: "Shoot schedule",
      unread: 1,
      last: "Can we shoot Friday 8:30 AM before open?",
      time: "22:50",
    },
    {
      id: "t_603",
      from: "Push Ops",
      subject: "New policy update",
      unread: 1,
      last: "Consent log retention updated to 18 months",
      time: "20:12",
    },
  ],
  payments: {
    next_payout: 315,
    pending: 129,
    paid_30d: 2740,
    failed_tx: 1,
    payout_breakdown: [
      { label: "Creator Fees", value: 1680 },
      { label: "Performance Bonus", value: 480 },
      { label: "Refunds", value: -69 },
      { label: "Platform Fees", value: 649 },
    ],
  },
  billing: {
    plan: "Growth",
    monthly_fee: 69,
    usage_fees: 248,
    next_invoice_date: "2026-05-01",
    status: "Scheduled",
    invoices: [
      { id: "INV-0426-001", date: "2026-04-01", amount: 312, paid: true },
      { id: "INV-0326-001", date: "2026-03-01", amount: 288, paid: true },
      { id: "INV-0226-001", date: "2026-02-01", amount: 254, paid: true },
    ],
  },
  integrations: [
    { name: "Square POS", status: "Connected", health: 98, last_sync: "23:40" },
    { name: "Instagram Business", status: "Connected", health: 95, last_sync: "21:14" },
    { name: "QuickBooks", status: "Needs Re-auth", health: 42, last_sync: "09:11" },
    { name: "Resend Email", status: "Connected", health: 99, last_sync: "00:02" },
  ],
  notifications: [
    {
      id: "n_701",
      title: "3 new high-score applicants",
      severity: "Info",
      detail: "Profiles above 88 match score are waiting for review.",
      time: "00:05",
    },
    {
      id: "n_702",
      title: "QuickBooks re-auth required",
      severity: "Warning",
      detail: "Reconnect within 48h to avoid billing export interruption.",
      time: "Yesterday",
    },
    {
      id: "n_703",
      title: "Dispute d_501 escalated",
      severity: "Critical",
      detail: "Fraud pattern confidence reached 0.71, review suggested.",
      time: "Yesterday",
    },
  ],
  settings: {
    profile_name: "Bodega Azul",
    timezone: "America/New_York",
    currency: "USD",
    language: "English",
    alerts: {
      application_alerts: true,
      payout_alerts: true,
      fraud_alerts: true,
      weekly_digest: true,
    },
  },
};
